In [1]:
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like

from pandas_datareader import data, wb
import pandas_datareader.data as web

import numpy as np
import datetime as dt

import yfinance as yf

/usr/local/lib/python3.10/dist-packages/yfinance/base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _empty_series = pd.Series()

Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)

In [2]:
start = dt.datetime(2015, 1, 1)
end = dt.datetime.today()
start

datetime.datetime(2015, 1, 1, 0, 0)

Step 3. Select the Apple, Tesla, Twitter, IBM, LinkedIn stocks symbols and assign them to a variable called stocks

In [3]:
stocks = ['AAPL', 'TSLA', 'TWTR', 'IBM', 'LNKD']

In [4]:
stocks

['AAPL', 'TSLA', 'TWTR', 'IBM', 'LNKD']

Step 4. Read the data from google, assign to df and print it

> Indented block

In [10]:
df =yf.download(["AAPL", "TSLA", "X", "IBM", "SNOW","CRM"], start="2015-01-01", end="2024-02-29")
df

[*********************100%%**********************]  6 of 6 completed

Price        Adj Close                                                  \
Ticker            AAPL         CRM         IBM        SNOW        TSLA
Date
2015-01-02   24.435266   59.240002  103.354836         NaN   14.620667
2015-01-05   23.746887   58.169998  101.728569         NaN   14.006000
2015-01-06   23.749121   57.200001   99.534653         NaN   14.085333
2015-01-07   24.082134   56.930000   98.884155         NaN   14.063333
2015-01-08   25.007429   58.590000  101.033401         NaN   14.041333
...                ...         ...         ...         ...         ...
2024-02-22  184.369995  293.649994  184.210007  225.619995  197.410004
2024-02-23  182.520004  292.799988  185.720001  229.339996  191.970001
2024-02-26  181.160004  300.390015  184.130005  230.929993  199.399994
2024-02-27  182.630005  299.500000  184.869995  234.029999  199.729996
2024-02-28  181.419998  299.769989  185.300003  230.000000  202.039993

Price                       Close                                      ...  \
Ticker              X        AAPL         CRM         IBM        SNOW  ...
Date                                                                   ...
2015-01-02  24.600361   27.332500   59.240002  154.933075         NaN  ...
2015-01-05  23.453142   26.562500   58.169998  152.495224         NaN  ...
2015-01-06  22.740767   26.565001   57.200001  149.206497         NaN  ...
2015-01-07  22.796272   26.937500   56.930000  148.231354         NaN  ...
2015-01-08  23.295866   27.972500   58.590000  151.453156         NaN  ...
...               ...         ...         ...         ...         ...  ...
2024-02-22  46.520000  184.369995  293.649994  184.210007  225.619995  ...
2024-02-23  47.259998  182.520004  292.799988  185.720001  229.339996  ...
2024-02-26  47.650002  181.160004  300.390015  184.130005  230.929993  ...
2024-02-27  47.380001  182.630005  299.500000  184.869995  234.029999  ...
2024-02-28  47.509998  181.419998  299.769989  185.300003  230.000000  ...

Price             Open                                        Volume  \
Ticker             IBM        SNOW        TSLA          X       AAPL
Date
2015-01-02  154.216064         NaN   14.858000  27.190001  212818400
2015-01-05  154.177826         NaN   14.303333  26.170000  257142000
2015-01-06  152.648178         NaN   14.004000  25.370001  263188400
2015-01-07  150.286804         NaN   14.223333  24.930000  160423600
2015-01-08  149.369019         NaN   14.187333  24.900000  237458000
...                ...         ...         ...        ...        ...
2024-02-22  182.449997  224.139999  194.000000  46.250000   52292200
2024-02-23  184.899994  234.279999  195.309998  46.590000   45074500
2024-02-26  185.600006  229.330002  192.289993  47.000000   40867400
2024-02-27  184.160004  233.000000  204.039993  47.639999   54318900
2024-02-28  184.630005  230.750000  200.419998  47.240002   48894200

Price
Ticker           CRM      IBM        SNOW       TSLA         X
Date
2015-01-02   2796400  5779673         NaN   71466000   4624000
2015-01-05   3688200  5104898         NaN   80527500   6565300
2015-01-06   3174900  6429448         NaN   93928500  10087200
2015-01-07   4284300  4918083         NaN   44526000   5151800
2015-01-08   3756600  4431693         NaN   51637500   6054600
...              ...      ...         ...        ...       ...
2024-02-22   5264300  5078400   5847700.0   92739500   4049500
2024-02-23   4414100  3432900   4517500.0   78670300   2710400
2024-02-26   8719300  4620800   4820600.0  111747100   4269400
2024-02-27   6178800  3641400   4810300.0  108645400   2392700
2024-02-28  12058000  3215100  18581600.0   99588500   2359300

[2304 rows x 36 columns]

Step 5. What is the type of structure of df ?

In [12]:
df.shape

(2304, 36)

Step 6. Print all the Items axis values

In [17]:
df.items

<bound method DataFrame.items of Price        Adj Close                                                  \
Ticker            AAPL         CRM         IBM        SNOW        TSLA
Date
2015-01-02   24.435266   59.240002  103.354836         NaN   14.620667
2015-01-05   23.746887   58.169998  101.728569         NaN   14.006000
2015-01-06   23.749121   57.200001   99.534653         NaN   14.085333
2015-01-07   24.082134   56.930000   98.884155         NaN   14.063333
2015-01-08   25.007429   58.590000  101.033401         NaN   14.041333
...                ...         ...         ...         ...         ...
2024-02-22  184.369995  293.649994  184.210007  225.619995  197.410004
2024-02-23  182.520004  292.799988  185.720001  229.339996  191.970001
2024-02-26  181.160004  300.390015  184.130005  230.929993  199.399994
2024-02-27  182.630005  299.500000  184.869995  234.029999  199.729996
2024-02-28  181.419998  299.769989  185.300003  230.000000  202.039993

Price                       Close                                      ...  \
Ticker              X        AAPL         CRM         IBM        SNOW  ...
Date                                                                   ...
2015-01-02  24.600361   27.332500   59.240002  154.933075         NaN  ...
2015-01-05  23.453142   26.562500   58.169998  152.495224         NaN  ...
2015-01-06  22.740767   26.565001   57.200001  149.206497         NaN  ...
2015-01-07  22.796272   26.937500   56.930000  148.231354         NaN  ...
2015-01-08  23.295866   27.972500   58.590000  151.453156         NaN  ...
...               ...         ...         ...         ...         ...  ...
2024-02-22  46.520000  184.369995  293.649994  184.210007  225.619995  ...
2024-02-23  47.259998  182.520004  292.799988  185.720001  229.339996  ...
2024-02-26  47.650002  181.160004  300.390015  184.130005  230.929993  ...
2024-02-27  47.380001  182.630005  299.500000  184.869995  234.029999  ...
2024-02-28  47.509998  181.419998  299.769989  185.300003  230.000000  ...

Price             Open                                        Volume  \
Ticker             IBM        SNOW        TSLA          X       AAPL
Date
2015-01-02  154.216064         NaN   14.858000  27.190001  212818400
2015-01-05  154.177826         NaN   14.303333  26.170000  257142000
2015-01-06  152.648178         NaN   14.004000  25.370001  263188400
2015-01-07  150.286804         NaN   14.223333  24.930000  160423600
2015-01-08  149.369019         NaN   14.187333  24.900000  237458000
...                ...         ...         ...        ...        ...
2024-02-22  182.449997  224.139999  194.000000  46.250000   52292200
2024-02-23  184.899994  234.279999  195.309998  46.590000   45074500
2024-02-26  185.600006  229.330002  192.289993  47.000000   40867400
2024-02-27  184.160004  233.000000  204.039993  47.639999   54318900
2024-02-28  184.630005  230.750000  200.419998  47.240002   48894200

Price
Ticker           CRM      IBM        SNOW       TSLA         X
Date
2015-01-02   2796400  5779673         NaN   71466000   4624000
2015-01-05   3688200  5104898         NaN   80527500   6565300
2015-01-06   3174900  6429448         NaN   93928500  10087200
2015-01-07   4284300  4918083         NaN   44526000   5151800
2015-01-08   3756600  4431693         NaN   51637500   6054600
...              ...      ...         ...        ...       ...
2024-02-22   5264300  5078400   5847700.0   92739500   4049500
2024-02-23   4414100  3432900   4517500.0   78670300   2710400
2024-02-26   8719300  4620800   4820600.0  111747100   4269400
2024-02-27   6178800  3641400   4810300.0  108645400   2392700
2024-02-28  12058000  3215100  18581600.0   99588500   2359300

[2304 rows x 36 columns]>

Step 7. Good, now we know the data avaiable. Create a dataFrame called

*   List item
*   List item

vol, with the Volume values.

In [20]:
#slice at volume
vol = df['Volume']
vol

Ticker           AAPL       CRM      IBM        SNOW       TSLA         X
Date
2015-01-02  212818400   2796400  5779673         NaN   71466000   4624000
2015-01-05  257142000   3688200  5104898         NaN   80527500   6565300
2015-01-06  263188400   3174900  6429448         NaN   93928500  10087200
2015-01-07  160423600   4284300  4918083         NaN   44526000   5151800
2015-01-08  237458000   3756600  4431693         NaN   51637500   6054600
...               ...       ...      ...         ...        ...       ...
2024-02-22   52292200   5264300  5078400   5847700.0   92739500   4049500
2024-02-23   45074500   4414100  3432900   4517500.0   78670300   2710400
2024-02-26   40867400   8719300  4620800   4820600.0  111747100   4269400
2024-02-27   54318900   6178800  3641400   4810300.0  108645400   2392700
2024-02-28   48894200  12058000  3215100  18581600.0   99588500   2359300

[2304 rows x 6 columns]

Step 8. Aggregate the data of Volume to weekly

In [25]:
vol['week'] = vol.index.week

week = vol.groupby(['week','year']).sum()
week

<ipython-input-25-c2f64b47c9c5>:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  vol['week'] = vol.index.week
<ipython-input-25-c2f64b47c9c5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vol['week'] = vol.index.week

Ticker           AAPL       CRM       IBM        SNOW       TSLA         X
week year
1    2015   212818400   2796400   5779673         0.0   71466000   4624000
     2016  1375160800  21706400  26415265         0.0  314631000  47565100
     2017   415382000  26563400  12492901         0.0  428646000  63484700
     2018   544687600  21934200  32822330         0.0  445702500  51865300
     2019   992756000  24270800  21924996         0.0  733350000  48963500
...               ...       ...       ...         ...        ...       ...
52   2021   340248100  15538100  18499200   7818800.0  275398500  46226300
     2022   307184100  27809600  10477100  12041300.0  809414500  16467000
     2023   153685700  13270000   9603900  16017200.0  407622000  15423000
53   2015   495046000   8835300  14161375         0.0  160807500  29731100
     2020   441102200  23280000  14703517  17529000.0  443055900  34277700

[479 rows x 6 columns]

Step 9. Find all the volume traded in the year of 2015

In [26]:
vol['year'] = vol.index.year

year = vol.groupby(['year']).sum()
year

<ipython-input-26-0c2f84e880b3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vol['year'] = vol.index.year

Ticker,AAPL,CRM,IBM,SNOW,TSLA,X,week
year,,,,,,,
2015,52264199600,1046573200,1156439400,0.000000e+00,16323267000,2478588800,6886
2016,38729911200,1450336300,1065461565,0.000000e+00,17435425500,4165298800,6684
2017,27243106000,1106801900,1120440154,0.000000e+00,23850471000,4039251800,6679
2018,34156144800,1461967800,1431514599,0.000000e+00,32424582000,2476480500,6633
2019,28254942800,1423022700,990437937,0.000000e+00,34620726000,3202830100,6677
2020,39863855600,1903444600,1468958052,3.400520e+08,57158737200,3543240000,6886
2021,22812206100,1552919700,1402480072,9.955773e+08,20708071500,5341272900,6684
2022,22065504500,1926935300,1256844400,1.625699e+09,21821019600,3441524300,6655
2023,14804257200,1616243100,1114005600,1.345712e+09,34330556300,1902727400,6655
2024,2212058800,209682500,212099400,2.205228e+08,4277396000,178283900,195